# Generated by Django 3.2.10 on 2021-12-26 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0007_organizationadress'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=30)),
                ('neighborhood', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('country', models.CharField(default='Brasil', max_length=30)),
                ('coordinates', models.CharField(max_length=30, null=True)),
                ('number', models.CharField(max_length=20)),
                ('complement', models.CharField(max_length=40, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
