# Generated by Django 3.2.10 on 2021-12-27 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_customeradress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeradress',
            name='owner',
        ),
        migrations.CreateModel(
            name='AdressAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_associated', models.BooleanField(default=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.customer')),
                ('customerAdress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.customeradress')),
            ],
        ),
        migrations.AddField(
            model_name='customeradress',
            name='owner',
            field=models.ManyToManyField(through='profiles.AdressAssociation', to='profiles.Customer'),
        ),
    ]
